- tests/tactics/Unfold.v
- theories/Libs/Analysis/ContinuityDomainNat.v
- theories/Libs/Analysis/ContinuityDomainR.v
- theories/Libs/Analysis/OpenAndClosed.v
- theories/Libs/Analysis/Sequences.v
- theories/Libs/Analysis/SequencesMetric.v
- theories/Libs/Analysis/SubsequencesMetric.v
- theories/Libs/Analysis/SupAndInf.v
- theories/Tactics/Unfold.v
For internal use by Waterproof editor only.
> Added tactic for unfolding that prints a message instead of throwing an errror.

- tests/libs/Analysis/StrongInductionIndexSequence.v
- theories/Libs/Analysis/StrongInductionIndexSequence.v
- theories/Util/Goals.v
- able to use property 'P(n(k)) = blue'
- able to use notation 'n(k)' later on in proof
- suggest 'n_0' instead of 'n0' to be more in line with suggested 'n_kplus1'
> Fix for problems with strong induction for defining index sequence.

- theories/Util/Since.v
The 'match!' statement allows for matching on types and thus we can get rid of the nested `match constr_equal` expressions.
> Rewrite the 'match' statement in Since.v to 'match!'

- src/databases.mlg
- theories/Automation/Framework.v
- theories/Waterproof.v
Note that both lines where loading the same plugin, but activating different syntax rules; that's not really allowed as it leaves the system in a partial state. If something like that is needed, true two plugins are necessary (Which is not hard to support nowadays).
> [build] Fix use of plugin aliases in findlib loading.

- tests/tactics/Induction.v
- tests/tactics/Obtain.v
- theories/Tactics/Induction.v
- theories/Tactics/Obtain.v
Coq lsp reads the input
```
Obtain such an
Qed.
```
as a single line, `Obtain such an Qed.`
This causes issues in the Waterproof editor: since (presumably) the line with `Qed.` in it does not throw an error, the bar to the side of the proof in the editor colors green, which normally indicates that the proof is complete.
This issue might be fixed when binders are incorporated into the `Obtain`-tactic, but we might wish to keep this check in order to produce non-confusing errors.
> fix: Throw fake syntax error if user-input is read as e.g. "Obtain such a Qed."

- tests/tactics/Postpone.v
- theories/Tactics/Conclusion.v
- theories/Tactics/ItHolds.v
Add options to postpone proof to 'It holds' and 'We conclude' tactics.
Lines with postponed proof give warnings reminding user that they still need to give an actual proof.
example usage:
```
By magic it holds that (0 = 0).  (* difficult yet true claim *)
By magic it holds that (0 = 1).  (* impossible claim *)
``` 
```
By magic we conclude that (0 = 1).
```
> feat: Tactics for postponing proof of statement.

- tests/tactics/Unfold.v
- theories/Libs/Analysis/ContinuityDomainNat.v
- theories/Libs/Analysis/ContinuityDomainR.v
- theories/Libs/Analysis/OpenAndClosed.v
- theories/Libs/Analysis/Sequences.v
- theories/Libs/Analysis/SequencesMetric.v
- theories/Libs/Analysis/SubsequencesMetric.v
- theories/Libs/Analysis/SupAndInf.v
- theories/Tactics/Unfold.v
Example usage:
```
Definition foo : nat := 0.
Goal (foo = 0) -> (foo = 2) -> (foo = 1).
Proof.
intros.
Expand the definition of foo.
Abort.
```
outputs the message
```
Expanded definition in statements where applicable.
To include these statements, use (one of):
We need to show that (0 = 1).
It holds that (0 = 0).
It holds that (0 = 2).
```
and throws an error stating that the `Expand definition` line needs to be removed in the final proof.
> feat: 'Expand definition' tactic unfolds definition in all statements

- _CoqProject.in
- src/g_waterproof.mlg
- src/waterproof.mlpack
- src/wp_evars.ml
- src/wp_evars.mli
- tests/tactics/Choose.v
- tests/tactics/Specialize.v
- tests/util/Evars.v
- theories/Tactics/Choose.v
- theories/Tactics/ItHolds.v
- theories/Tactics/Specialize.v
- theories/Util/Evars.v
Allow for choosing blanks in specialize statements. For example:
```
Goal (forall a b c : nat, a + b + c = 0) -> False.
Proof.
intro H.
Use a := _, b := _, c := _ in (H).
It holds that (?a + ?b + ?c = 0).
```
When a user provides a blank for postponing the choice of a variable, the tactic automatically creates a variable (an evar) with a name based on the binder name that was selected.
The PR includes renaming of evars also for the choose tactic.
> Specialize blank

- tests/tactics/Choose.v
- tests/tactics/Specialize.v
- tests/tactics/Take.v
- theories/Tactics/Choose.v
- theories/Tactics/Take.v
Check for binder names in Choose and Take tactics.
For instance
```
Goal exists n : nat, n + 1 = n + 1.
Choose m := 1.
Abort.
```
generates a warning, as does
```
Goal forall n : nat, n = n.
Proof.
Take m : nat.
Abort.
```
> Feat binders

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
Using the devcontainer should be useful for instance in using github codespaces for editing the project, but mostly this is a tryout for creating a devcontainer for waterproof exercise sheets.
> Create a devcontainer for the project

- _CoqProjectForMake
- src/exceptions.ml
- src/exceptions.mli
- src/g_waterproof.mlg
- src/wp_ffi.ml
- tests/libs/Analysis/StrongInductionIndexSequence.v
- tests/tactics/Choose.v
- tests/tactics/Conclusion.v
- tests/tactics/Help.v
- tests/tactics/Postpone.v
- tests/tactics/Specialize.v
- tests/tactics/Take.v
- tests/tactics/Unfold.v
- tests/util/Assertions.v
- tests/util/MessagesToUser.v
- theories/Libs/Analysis.v
- theories/Libs/Analysis/ContinuityDomainNat.v
- theories/Libs/Analysis/ContinuityDomainR.v
- theories/Libs/Analysis/LimsupLiminfBolzano.v
- theories/Libs/Analysis/OpenAndClosed.v
- theories/Libs/Analysis/Sequences.v
- theories/Libs/Analysis/SequentialAccumulationPoints.v
- theories/Libs/Analysis/Series.v
- theories/Libs/Analysis/Subsequences.v
- theories/Libs/Analysis/SupAndInf.v
- theories/Tactics/Choose.v
- theories/Tactics/Help.v
- theories/Util/Assertions.v
- theories/Util/MessagesToUser.v
The core new functions are `assert_fails_with_string` and `assert_feedback_with_strings`.
```
assert_feedback_with_strings (fun () =>
warn (Message.of_string "first warning");
warn (Message.of_string "second warning"))
Warning
["first warning"; "second warning"].
```
```
assert_fails_with_string
(fun () => throw (Message.of_string "This error _should_ be raised."))
"This error _should_ be raised.".
```
We also added more channels for feedback (inform, notice ...) and added a possibility for logging general feedback.
We have removed all warnings during library compilation.
> Feat test warnings and errors

- _CoqProjectForMake
- tests/tactics/Choose.v
- tests/tactics/Obtain.v
- tests/tactics/Take.v
- theories/Libs/Analysis/LimsupLiminfBolzano.v
- theories/Libs/Analysis/Sequences.v
- theories/Libs/Analysis/SubsequencesMetric.v
- theories/Tactics/Choose.v
- theories/Tactics/Obtain.v
- theories/Tactics/Take.v
- theories/Util/Assertions.v
- theories/Util/Binders.v
At first I thought this wouldn't be necessary, until I needed to obtain five variables for a lemma...
Allows for:
```
Goal (exists n m k l : nat, n + k + 1 = l + m)%nat -> True.
Proof.
intro H.
Obtain such an n, m, k, l.
Abort.
```
The tactic now also warns on unexpected variable names.
> Feat obtain multiple vars + warn on unexpected variable names.

- tests/tactics/Choose.v
- tests/tactics/Specialize.v
- theories/Notations/Common.v
- theories/Util/Evars.v
This seems to fix the problem with evars that get automatically resolved, at the expense of a slightly more complicated notation (`!?n` rather than `?n`). Different choices for the notation could be made.
Edit: in later commit, suggested the notation `?n?` over `!?n`.
> Possible fix for automatically resolving evars

- tests/tactics/Unfold.v
- theories/Tactics/Unfold.v
Small fix to improve the interlacing with the editor on certain types of unfold messages.
> Split unfold messages so the behavior in the editor is better

- tests/tactics/Choose.v
- tests/tactics/Postpone.v
- tests/tactics/Specialize.v
- theories/Tactics/Choose.v
- theories/Tactics/Conclusion.v
- theories/Tactics/ItHolds.v
- theories/Tactics/ItSuffices.v
- theories/Tactics/Specialize.v
- theories/Util/Goals.v
There was be a bug that sometimes the goal could be closed after having chosen a blank, or after using magic. This is now fixed by adding a goal (a custom version of `False`) and admitting it.
> Fix that goals can be closed after choosing blanks or using magic

- tests/tactics/Choose.v
- theories/Libs/Analysis/LimsupLiminfBolzano.v
- theories/Libs/Analysis/SequentialAccumulationPoints.v
- theories/Libs/Analysis/SupAndInf.v
- theories/Tactics/Choose.v
- theories/Tactics/Define.v
- theories/Tactics/Specialize.v
by replacing `set a := x` by `pose a := x`
> Prevent automatic rewriting of terms in proof goal matching new definition.

- coq-waterproof.opam
- tests/tactics/Unfold.v
- theories/Libs/Analysis/OpenAndClosed.v
- theories/Libs/Analysis/Sequences.v
* Excludes certain architectures / operating systems in the opam file
* Fixes an old definition of open
* Fixes #99 . That issue seems to only occur for definitions in this particular file (`Sequences.v`): it was not adapted yet to give it full functionality with the new unfold syntax.
> Small fixes

- .github/workflows/build-with-make.yml
- .github/workflows/build.yml
In the CI, now pull the dev docker image from rocq/rocq-prover because it is no longer available at the previous repository.
> Fix docker image

- theories/Libs/Analysis/ContinuityDomainNat.v
- theories/Libs/Analysis/ContinuityDomainR.v
- theories/Libs/Analysis/MetricSpaces.v
- theories/Libs/Analysis/OpenAndClosed.v
- theories/Libs/Analysis/Sequences.v
- theories/Libs/Analysis/StrongInductionIndexSequence.v
- theories/Libs/Analysis/SubsequencesMetric.v
- theories/Libs/Negation.v
- theories/Tactics/Assume.v
- theories/Tactics/Because.v
- theories/Tactics/Conclusion.v
- theories/Tactics/Contradiction.v
- theories/Tactics/Either.v
- theories/Tactics/Help.v
- theories/Tactics/ItSuffices.v
- theories/Tactics/Obtain.v
- theories/Tactics/Specialize.v
- theories/Tactics/Take.v
- theories/Tactics/ToShow.v
- theories/Tactics/Unfold.v
- theories/Util/Assertions.v
- theories/Util/Binders.v
- theories/Waterprove.v
Warnings were fixed on branch 8.20, and the corresponding changes can be merged in coq-master. In particular:
* Unused variable warnings
* Warnings about arbitrary terms in `using` clause
* Incompatible prefix warnings
> Fix warnings from 8.20

- .gitignore
- Developer-instructions.md
- dune-project
- tests/test-folder.py
- theories/dune
Improve the testing setup: Let dune look for the correct dependencies of the tests, and work with variable names for the workspace and project roots. It also bumps the dune version, and adds Ltac2 as a dependency.
For this to work, one should create a symlink to waterproof-exercises in the coq-waterproof directory.
> Backport changes for tests

- tests/test-folder.py
In the previous version, the fcc script was using the installed coq-waterproof version, not the one that was just being built. This should be fixed now by changing the root of the script.
> Fix the root for fcc in the test script

- coq-waterproof.opam
We add coq back as a dependency in the `coq-waterproof.opam` file, because this seems necessary for a dune build
> Add Coq as a dependency (which seems necessary for a dune build)

- src/exceptions.ml
- src/exceptions.mli
- src/g_waterproof.mlg
Adds an error handler so the error messages that are being sent on Rocq errors can be slightly reformulated. These Rocq errors just fly through and we cannot catch them in Ltac2.
**Testing this pull request:**
I do not see a way to add automated tests for this addition at the moment. Testing should be done manually, by opening the tutorial and creating a syntax error, and by checking the tutorial at example 10, and changing `* Indeed, (1 / 2 > 0).` to `Indeed, (1 / 2 > 0).`.
> Filter errors to explain errors a bit more

- _CoqProjectForMake
- src/proofutils.ml
- src/waterproof.mlpack
- src/wp_bullets.ml
- src/wp_bullets.mli
- tests/util/Bullets.v
This PR adds two new bullet behaviors: `Waterproof Strict Subproofs` and `Waterproof Relaxed Subproofs`. The `Waterproof Strict Subproofs` behavior is the same as the standard behavior in Rocq (also called `Strict Subproofs`), except that the suggestion and error messages are a bit different. In contrast, with the `Waterproof Relaxed Subproofs` bullet behavior, one can write any bullet one wants: they all behave the same. The suggestion mechanism still tries to encourage some structure.
**Testing this PR:**
See the file `Bullets.v` for some tests. They should give some idea on experimenting further. Also note the messages/suggestions that are given after a proof is finished.
> Add bullet behavior

- tests/tactics/Assume.v
- tests/tactics/TakeSuchThat.v
- theories/Tactics/Assume.v
Example old syntax:
```
Assume that A /\ B as (i) and B /\ C and C /\ D and D /\ E as (ii) and E /\ F.
```
Example new syntax:
```
Assume that A /\ B as (i), B /\ C, C /\ D, D /\ E as (ii) and E /\ F.
```
Decided to **not** use the Oxford comma, but this can be changed easily.
> Natural formulation for assuming multiple premises at once

- _CoqProjectForMake
- tests/tactics/ItHolds.v
- theories/Tactics/Conclusion.v
- theories/Tactics/ItHolds.v
- theories/Tactics/ItSuffices.v
- theories/Util/BySince.v
- theories/Util/TypeCorrector.v
- Renamed corresponding utilities file.
- Fixes in error messages
- Correct output when extra lemma had to be unsealed
- Suggestion to use By resp. Since in case of boolean input
- Added test case using assertion framework. This required reworking some of the control flow since the tactic gave different errors depending on whether redirecting of errors was enabled or disabled. The old control flow assumed that errors thrown with Waterproof's `throw`-function would be non-catchable.
> Small update 'By/Since ... it holds that' tactic

- tests/tactics/Take.v
- theories/Tactics/Take.v
- theories/Util/Assertions.v
Improves error messages on `Take`, and in particular fixes #134
For impression of improvement, see the new tests in `tests/tactics/Take.v`.
> Improve error messages for Take tactic

- tests/test-folder.py
This will allow us to mark expected failures of tests using a file with the same name as the .mv-file except ending in .test instead. This file contains a list of expected messages in order, for which the corresponding diagnostics are then not considered failures for purposes of testing.
> Allow preconfigured failures
